# Generated by Django 3.2.5 on 2021-08-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'male'), ('OTHER', 'other')], default='sex', max_length=11),
        ),
    ]
